version: '3'

services:
    mysql:
        image: mysql:5.7
        container_name: mysql-server
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: crawl_telegram
            TZ: 'Asia/Bangkok'
        volumes:
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./db/data:/var/lib/mysql
            - ./db/sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        env_file:
            - .env
